### ISSUE TITLE
Error: Could not find resource 'Class[Openvpn::Install]' for relationship on 'Openvpn::Server'

### ISSUE THREAD

**Issue by pbenefice** [voxpupuli/puppet-openvpn#258]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
```
$ puppet --version
5.3.3
```
- Ruby: 
```
$ facter rubysitedir rubyversion
rubysitedir => /opt/puppetlabs/puppet/lib/ruby/site_ruby/2.4.0
rubyversion => 2.4.2
```
- Distribution: 
```
$ uname -a
Linux OpenVPN 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux
```
- Module version:
```
$ git submodule status modules/openvpn/
 abbd32bec5bf95eb067284f901807eb65e61e2d9 modules/openvpn (v1.0-605-gabbd32b)
```

## How to reproduce (e.g Puppet code you use)

For example I used the same code as issue 188 : 

```
class my_openvpn {
  openvpn::server { 'admin_openvpn_server':
    country      => 'FR',
    province     => 'FR',
    city         => 'France',
    organization => 'xxxxxxxxx',
    email        => 'xxxxxxxxx',
    server       => '10.0.0.1 255.255.255.0',
  }
}
```

## What are you seeing

The warnings & error I'm getting is the following :   
```
Warning: Unknown variable: '::openvpn::params::systemd'. at /home/git/data_servers/modules/openvpn/manifests/server.pp:518:6
Warning: Unknown variable: '::openvpn::manage_service'. at /home/git/data_servers/modules/openvpn/manifests/server.pp:522:6
Warning: Unknown variable: '::openvpn::params::pam_module_path'. at /home/git/data_servers/modules/openvpn/manifests/server.pp:551:22
Warning: Unknown variable: '::openvpn::params::etc_directory'. at /home/git/data_servers/modules/openvpn/manifests/server.pp:552:20
Warning: Unknown variable: '::openvpn::params::root_group'. at /home/git/data_servers/modules/openvpn/manifests/server.pp:553:17
Warning: Unknown variable: 'openvpn::params::group'. at /home/git/data_servers/modules/openvpn/manifests/server.pp:556:16
Warning: Unknown variable: '::openvpn::autostart_all'. at /home/git/data_servers/modules/openvpn/manifests/server.pp:652:35
Warning: Unknown variable: '::openvpn::params::systemd'. at /home/git/data_servers/modules/openvpn/manifests/server.pp:692:6
Warning: Unknown variable: '::openvpn::params::namespecific_rclink'. at /home/git/data_servers/modules/openvpn/manifests/server.pp:706:6
Warning: Unknown variable: 'openvpn::params::group'. at /home/git/data_servers/modules/openvpn/manifests/ca.pp:112:16
Warning: Unknown variable: '::openvpn::params::etc_directory'. at /home/git/data_servers/modules/openvpn/manifests/ca.pp:120:20
Warning: Unknown variable: 'openvpn::params::easyrsa_source'. at /home/git/data_servers/modules/openvpn/manifests/ca.pp:123:30
Warning: Unknown variable: 'openvpn::params::link_openssl_cnf'. at /home/git/data_servers/modules/openvpn/manifests/ca.pp:156:6
Error: Could not find resource 'Class[Openvpn::Install]' for relationship on 'Openvpn::Server[admin_openvpn_server]' on node openvpn.xxx.local
```

and when using `--trace` I get the following additional logs : 
```
Error: Could not find resource 'Class[Openvpn::Install]' for relationship on 'Openvpn::Server[admin_openvpn_server]' on node openvpn.xxx.local
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/relationship.rb:40:in `mk_relationship'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/relationship.rb:21:in `block (2 levels) in evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/relationship.rb:20:in `each'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/relationship.rb:20:in `block in evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/relationship.rb:19:in `each'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/relationship.rb:19:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:392:in `block in evaluate_relationships'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:392:in `each'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:392:in `evaluate_relationships'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:623:in `finish'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:183:in `block (2 levels) in compile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:183:in `block in compile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:263:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:153:in `compile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:33:in `compile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:297:in `block (2 levels) in compile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:295:in `block in compile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:224:in `block in benchmark'
/opt/puppetlabs/puppet/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:223:in `benchmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:293:in `compile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:52:in `find'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:195:in `find'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:262:in `block in main'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:263:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:233:in `main'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:174:in `run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:358:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:666:in `exit_on_fail'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:358:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:132:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:72:in `execute'
/opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
```

## Additional Infos : 
- I don't use hiera, only .pp files
- The manifest works great on a local debian VM (using vagrant), my issue is on a recently installed debian VM under Hyper V
- I also tried under a ubuntu Hyper V VM and I got the same issue
- Seems similar to this [Issue:188](https://github.com/voxpupuli/puppet-openvpn/issues/188)

Any help would be appreciated, thanks in advance!

**Comment by pbenefice** [comment]
Any news on this issue ? 
Did you have time to get a look at it ?
Thanks.

**Comment by Dan33l** [comment]
I digged a bit about diff between `2.9.0` and `3.0.0` tags of openvpn module. The reporter of #188 was reporting it happened when changed module from `2.9.0` to `3.0.0`.

I found only one possible interesting peace of code : 
```
--- a/manifests/init.pp
+++ b/manifests/init.pp

@@ -55,8 +98,15 @@ class openvpn(
   if ! $::openvpn::params::systemd {
     class { 'openvpn::service':
       subscribe => [Class['openvpn::config'], Class['openvpn::install'] ],
-      before    => Class['openvpn'],
+    }
+    if empty($servers) {
+      Class['openvpn::service'] -> Class['openvpn']
     }
   }
```

When i tryed to reproduce with same code proposed in `How to reproduce section` i got error related to concat missing argument.

@pbenefice  please give the versions of extra modules you are using. IE : 
 * mod `puppetlabs/concat`
 * mod `puppetlabs/stdlib`

**Comment by pbenefice** [comment]
Hi @Dan33l, 

Thanks for you interest. Sadly this issue was a related to specific equipment I had access to at work, which is not the case anymore.
I won't be able to reproduce the problem.

But thanks anyway.
